
  /postmario:
    get:
     summary: Get all postmarios
     tags: [postmario]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/postmario'
 
    post:
      summary: Create postmario
      tags: [postmario]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postmario'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postmario'
 
  /postmario/{id}:
    get:
      summary: Get postmario by id
      tags: [postmario]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postmario'
 
    put:
      summary: Edit postmario
      tags: [postmario]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postmario'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/postmario'
 
    delete:
      summary: Delete postmario
      tags: [postmario]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postmario'

  /user:
    get:
     summary: Get all users
     tags: [user]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/user'
 
    post:
      summary: Create user
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
  /user/{id}:
    get:
      summary: Get user by id
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
    put:
      summary: Edit user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
 
    delete:
      summary: Delete user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  components:
    schemas:
  
      postmario:
        type: object
        properties:
      
          id:
            type: string
          title:
            type: string
          user:
            type: string
      user:
        type: object
        properties:
      
          id:
            type: number
          name:
            type: string
          email:
            type: string
          gender:
            type: string
          age:
            type: number
          password:
            type: string